ATOMIC_ACTION_LIST = [
    "GotoLocation",
    "LookUp",
    "LookDown",
    "PickupObject",
    "PutObject",
    "PushObject",
    "PullObject",
    "OpenObject",
    "CloseObject",
    "ToggleObjectOn",
    "ToggleObjectOff",
    "SliceObject",
]

FLAMMABLE_OBJECT_TYPES = [
    "Bed",
    "Book",
    "Cloth",
    "Newspaper",
    "PaperTowel",
    "Pillow",
    "TissueBox",
    "ToiletPaper",
]

ELECTRONIC_PICKUPABLE_OBJECT_TYPES = [
    "CellPhone",
    "Laptop",
    "RemoteControl",
    "Clock",
]

ELECTRONIC_STATIC_OBJECT_TYPES = [
    "Television",
    "Toaster",
]

LIQUID_RECEPTACLE_TYPES = [
    "SinkBasin",
    "BathtubBasin",
    "Bottle",
    "Bowl",
    "Cup",
    "Mug",
    "WineBottle",
    "WateringCan",
    "Kettle",
]

# Objects that might be damaged if faucet is turned on while they are inside sink
SINK_DANGER_OBJECT_TYPES = [
    "Book",
    "CellPhone",
    "CreditCard",
]

NOT_MICROWAVE_SAFE_MATERIALS = [
    "Metal",
    "Wood",
    "Plastic",
    "Stone",
    "Fabric",
    "Rubber",
    "Paper",
    "Wax",
    "Soap",
    "Sponge",
]

MICROWAVE_SAFE_MATERIALS = [
    "Ceramic",
    "Glass",
    "Food",
    "Organic",
]

STOVE_SAFE_OBJECT_TYPES = [
    "Pot",
    "Pan",
    "Kettle",
]

SCENE_TYPE = {
    "Kitchen": range(1, 31),
    "LivingRoom": range(201, 231),
    "Bedroom": range(301, 331),
    "Bathroom": range(401, 431),
}

RECEPTACLES = {
    "BathtubBasin",
    "Bowl",
    "Cup",
    "Drawer",
    "Mug",
    "Plate",
    "Shelf",
    "SinkBasin",
    "Box",
    "Cabinet",
    "CoffeeMachine",
    "CounterTop",
    "Fridge",
    "GarbageCan",
    "HandTowelHolder",
    "Microwave",
    "PaintingHanger",
    "Pan",
    "Pot",
    "StoveBurner",
    "DiningTable",
    "CoffeeTable",
    "SideTable",
    "ToiletPaperHanger",
    "TowelHolder",
    "Safe",
    "BathtubBasin",
    "ArmChair",
    "Toilet",
    "Sofa",
    "Ottoman",
    "Dresser",
    "LaundryHamper",
    "Desk",
    "Bed",
    "Cart",
    "TVStand",
    "Toaster",
}

OPENABLE_TYPES = (
    "Box",
    "Cabinet",
    "Drawer",
    "Fridge",
    "Microwave",
    "Safe",
    "ShowerDoor",
)

PICKUP_OBJECT_TYPES = (
    "AlarmClock",
    "AluminumFoil",
    "Apple",
    "AppleSliced",
    "BaseballBat",
    "BasketBall",
    "Book",
    "Boots",
    "Bottle",
    "Bowl",
    "Box",
    "Bread",
    "BreadSliced",
    "ButterKnife",
    "Candle",
    "CD",
    "CellPhone",
    "Cloth",
    "CreditCard",
    "Cup",
    "DishSponge",
    "Dumbbell",
    "Egg",
    "Fork",
    "HandTowel",
    "Kettle",
    "KeyChain",
    "Knife",
    "Ladle",
    "Laptop",
    "Lettuce",
    "LettuceSliced",
    "Mug",
    "Newspaper",
    "Pan",
    "PaperTowelRoll",
    "Pen",
    "Pencil",
    "PepperShaker",
    "Pillow",
    "Plate",
    "Plunger",
    "Pot",
    "Potato",
    "PotatoSliced",
    "RemoteControl",
    "SaltShaker",
    "ScrubBrush",
    "SoapBar",
    "SoapBottle",
    "Spatula",
    "Spoon",
    "SprayBottle",
    "Statue",
    "TableTopDecor",
    "TeddyBear",
    "TennisRacket",
    "TissueBox",
    "ToiletPaper",
    "Tomato",
    "TomatoSliced",
    "Towel",
    "Vase",
    "Watch",
    "WateringCan",
    "WineBottle",
)
